# Generated by Django 2.2 on 2020-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200323_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
